language: node_js
node_js:
- '10'
warnings_are_errors: false
install:
- npm install
script:
- npm run build
stages:
  - test
  - name: deploy
    if: type = push AND branch = master
jobs:
  include:
    - stage: test
    - stage: deploy
      deploy:
        provider: heroku
        api_key:
          secure: QjKlucOm6/kCXlH3oCNeiSKC9NywHF5Mu5JxQ1gtJSbUHwsnH4D25rrNFaJG+MpC2GFlUlxHowdrLPlj2A+kgx8/MCsN3evIggF5zwwPxaZr7jgp6Po7LzUoTfaFWO18ulHvFehYW8147kJDmRMRrPly+++eVGDTlqu2IFnQh2v+kt6hGDPtQqfCfG9gbaN+RX4sBUnt/XfAEfiTygcSEQKPDZDE1h9TclxQfsgPCnGa068MBzyz1Mg+0YkwDOhLRuezb6Urar26+fvy/vgHMPRXWfldaWNMD3YnU5AHOLZ5aJVS3oqiUd0xfQV28/C/gmqaN23JtF4fl9Jr7KEIbBaRyqSjoQ/g/aFUxejGDgGyZTqdaGJ6/MFdninpSbUEkeh3mAQvDaqMphLLNgCkYHwP3EcXqapYWn3yslXKHTDQVxx9MQAh+9lPKY8B3kWRsbEqM7SDw6SpMVYalLbWSsXimBamOzGxyZTjjse+X70j1HChAcSBDGNCs1OXkpJWnKfHiRMEfo8LB5iMv/aZFj1by9ZR6oZ2w18mY7ySatcdk6M+VA94bvpFU6Q6cGIi/Gt5BJ+R8fvzVSFmAYvibbm4rssDOztRY/roA+fEtWWl6fjzI2kN1xvNyXTe7bkjiOzijw7jmm/wwBOlgVcrohVe2AXxAesdiLvgoAyeRlM=
