language: node_js
node_js:
- '10'
warnings_are_errors: false
install:
- npm install
script:
- npm run build
stages:
  - test
  - name: deploy
    if: type = push AND branch = master
jobs:
  include:
    - stage: test
    - stage: deploy
      deploy:
        provider: firebase
        token:
          secure: H1gfzu6IYp80RdVYtCEqTptKaj7gCj0QIOtdZ0XDHb442ohPYiV0qOjTT8UM1VczmL74sqpxv4pUvcdKYPrVEnOVo5fRqM9u4xN8eYEfQb8UA3C2xAHGT7tr7fOuKfDt66vsdBxqP+E8coPud7QkETbLchbXF3c7W5kyte5jujUEgNG2AuCpesYXJBXYDuy8fgvvMK0xcymkjBqhyIisT0O9aIeW4FAgQnZ+2gitPN86eYsLrI4WG3fXpP18BQma+GCsG0nwHgVrTs8dJQlCjTXQ1UotJNyBRzf6dhXYnX/s1aQD2GT8SnSnoLsiOYxhX/WDQD75D3Vgs5zy+ngGNDjhPYg3Kjh+aXklYgxporaVrT1NUTOTJ1JEyUWyjBsziImMp+T6Xe23D/bTnx0hi/mGLbpw7E1+slVy5qVnb5jLjKN4up8XWspujcPtmm7pMkxWZGQXjxj+3XZ60Lo/ix9TRv4NcRvFeeAGmXQEoD5ETABEx+BItDK68dkkSGKNBTlhRv2/AjlODnXgmPgo/VlFxWT9ycHRh8cpzUpvxO1Sl6rCQ6WHe3T16oJyui5Z8axB8jwto3IziXG0DcajMeZ+WkMnpEBfszGuX9FsxLEB7zybbOeJFPlZrrvnVY8yCj/wOd7Ihghl6JkXhMLVL0m1cZnmaAkfDw7LdLwwaiQ=
